services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      # Main data directory - stores database, uploads, cache
      - open-webui-data:/app/backend/data
      # Optional: Store logs persistently
      - open-webui-logs:/app/backend/logs
      # Optional: If you want to backup your data locally
      # - ./backups:/backups
    environment:
      - ENABLE_SIGNUP=true
      # Optional: Set a custom data directory path
      - DATA_DIR=/app/backend/data
      # Optional: Enable automatic backups
      - ENABLE_OLLAMA_API=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      # This ensures Watchtower won't update during business hours if you use it
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  open-webui-data:
    name: open-webui-data
  open-webui-logs:
    name: open-webui-logs
