#!/bin/bash

echo "📦 Preparing repository for GitHub..."
echo ""
echo "To publish this repository to GitHub:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to: https://github.com/new"
echo "   - Name: open-webui-auto-update"
echo "   - Description: Automated update system for Open WebUI with data persistence"
echo "   - Make it public or private as desired"
echo "   - DO NOT initialize with README, license, or .gitignore"
echo ""
echo "2. After creating the empty repository, run these commands:"
echo ""
echo "   git remote add origin https://github.com/iantrimble/open-webui-auto-update.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Optional: Add topics to your repository:"
echo "   - open-webui"
echo "   - docker"
echo "   - automation"
echo "   - macos"
echo "   - backup"
echo "   - docker-compose"
echo ""
echo "Repository is ready for GitHub! 🚀"
